[certificates]
caCrt    = "gs://naesheim-home-terraform/keys/cluster_ca_certificate.crt"
caKey    = "gs://naesheim-home-terraform/keys/cluster_client_key.key"
caClient = "gs://naesheim-home-terraform/keys/client_certificate.crt"

[settings]
kubeContext = "k8s-gcloud"
username = "$CLUSTER_USERNAME"
password = "$CLUSTER_PASSWORD" 
clusterURI = "https://${ENDPOINT}"

[helmRepos]
  praqma = "https://praqma-helm-repo.s3.amazonaws.com/"
  jetstack = "https://charts.jetstack.io/"


[namespaces]
[namespaces.kube-system]
    installTiller = true
    tillerRole = "cluster-admin"

[namespaces.default]
    installTiller = true
    tillerRole = "cluster-admin"

# define the desired state of your applications helm charts
# each contains the following:

[apps]
    [apps.nginx-controller]
    name = "nginx-ingress"
    description = "nginx-controller"
    namespace = "kube-system"
    enabled = true
    chart = "stable/nginx-ingress"
    version = "1.19.0"

    [apps.cert-manager]
    name = "cert-manager"
    description = "cert-manager"
    namespace = "kube-system"
    enabled = true
    chart = "stable/cert-manager"
    version = "v0.6.7"

    [apps.cert-issuer]
    name = "cert-isser"
    description = "cert-isser"
    namespace = "kube-system"
    enabled = true
    chart = "praqma/cert-issuer"
    version = "1.0.0"
    valuesFile= "cert-issuer.yaml"
